### ISSUE TITLE
Click Emitter and Router link causes Problems with the Events.

### ISSUE THREAD

**Issue by dbidev** [DBIAnalytics/ABIS-SmartApp-SDK#5]
<button (click)="click.emit($event)" routerLink="{{link}}" [ngClass]="{'maxButton':lessStyle == false, 'maxButtonClean':lessStyle == true}" mat-raised-button>
  <mat-icon *ngIf="showButtonIcon">{{icon}}</mat-icon>{{text}}
</button>

**Comment by dbidev** [comment]
I have create a new command and pluged it into the card template. The UI behaves strange. I will need two clicks to close the dialog again. And it will route me to another page if not deactivated beforehand.  <app-button (click)="actionDispatcher.dispatch({name:'Abis.Cockpit.Command.Create'})" routerLink="-"
                  [text]="'New Command'"></app-button>

**Comment by jaensen** [comment]
1) The "app-button" should either have a [link] or  a (click) property. Not both at the same time.
2) Added $event.stopPropagation() to prevent the dialog from opening two times (quick fix - isn't the root problem)
